### PR TITLE
Improve serial port detection

### LINKED ISSUE #192: Improve Serial Port Detection
Currently, the serial ports are hard coded to ACM0 ACM1 ACM2 and ACM3. These are the most comment ports for our devices, but other devices or more/less devices would not work.

Added code to the "serial_ports" which checks all possible ports - this worked great but when actually using it when the connected devices there was considerable lag. We call it every 1 second ish and try to write to all those ports so... yeah.

Would be nice to detect whenever a device is plugged in or removed and update arduino_count accordingly (also need to handle other serial ports)

### PR DESCRIPTION
**Pull request by dallasbrittany**
Fixes #192 .

Changes proposed in this request:
- Adds and gives user a command line option to use config.json to specify serial ports with default devices expected
- If not using config.json, uses pyudev to automatically detect adding and removing Arduinos (this is the default option)
- Does not enforce having 4 serial ports to open; uses the serial port count for arduino_count
- Adds some constants at the top of GUI.py and adds some docstrings
- Adds some writes to logFile but also adds some prints to the screen for serial ports
- Tries to be better about using all caps for globals

@ISS-Mimic

### CODE REVIEW

**Comment by streadgold** [comment]
Did a little testing of this today - had some problems though. Whenever I tried transmitting via the mimic screen, the program completely locked up with no indication of data being sent to the arduino (RX LEDs, mega on ACM0).

[errors.txt](https://github.com/ISS-Mimic/Mimic/files/5514125/errors.txt)

Thoughts?

**Comment by dallasbrittany** [comment]
> errors.txt

Looks like I forgot to rename `serial_ports` to `SERIAL_PORTS` in that function. I just fixed it.

> File "GUI.py", line 171, in serialWrite
>      for s in serial_ports:
> NameError: name 'serial_ports' is not defined

**Comment by streadgold** [comment]
Now I'm getting a "'str' object has no attribute 'write'" error at line 173. Does it think "s" is a string not a serial port?

**Comment by dallasbrittany** [comment]
> Now I'm getting a "'str' object has no attribute 'write'" error at line 173. Does it think "s" is a string not a serial port?

Yes, that's exactly the problem. Could you tell me what steps you're taking to test that function? Whatever I'm doing isn't hitting it -- hopefully I actually can run it with my setup. Thanks so much for catching this.

**Comment by streadgold** [comment]
I sent +90 degrees to the 4B BGA via the manual control screen, and separately also tried the regular transmit through the mimic screen (same error both times)

**Comment by dallasbrittany** [comment]
I think I fixed the problem, but I can't test it right now because something seems to be wrong with my setup.

**Comment by streadgold** [comment]
Seems to work great! 

There's an error on line 81 about x being referenced before assignment, I assume it was meant to be indented inside the for loop, in which case everything seems to work well.

I'd still like to test this with the full setup before merging, but I think this will solve problems!

**Comment by dallasbrittany** [comment]
I think I'd rather delete it outside of the loop, so I just pushed another change to save idx_to_remove and use that instead of indexing with x. Glad the testing went better. Sorry for the hassle! I need to get my test setup working 100% and improve the lint results better so I can test better and catch dumb mistakes faster.

**Comment by streadgold** [comment]
We finally got around to testing this (and fixing mimic so we can test) and the new serial code works great mostly - we found one issue that seems to occur when a device is unplugged and plugged back in, or when the USB hub randomly changes the device IDs (which happens occasionally for.... reasons?) 

[errors.txt](https://github.com/ISS-Mimic/Mimic/files/5562270/errors.txt)

**Comment by streadgold** [comment]
Now getting an error on line 81 "local variable 'idx to remove' referenced before assignment"

**Comment by dallasbrittany** [comment]
Let's just go with what worked for you before. I moved the delete back into the loop.

**Comment by dallasbrittany** [comment]
Actually hold on, let me try something better.

**Pull request merged**
